name:                bugwalker
version:             0.1.0.0
github:              "corynz/bugwalker"
license:             MIT
author:              "Coryn"
maintainer:          "famdont@me"
copyright:           "2020 Coryn"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/corynz/bugwalker#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- servant-auth
- servant-auth-server
- servant-options
- wai
- wai-cors
- warp
- split
- http-conduit
- bytestring
- sqlite-simple >= 0.4
- uuid
- cryptonite
- text
- directory
- jose
- stm
- time  

library:
  source-dirs:
  - src
  - src/io
  - src/gamedata
  - src/webapi
  - src/utils
  - src/auth

executables:
  bugwalker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bugwalker

tests:
  bugwalker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bugwalker
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
